### PR TITLE
Fix/servicenow connector defects

### LINKED ISSUE #3094: [BUG] ServiceNow: a revoked knowledge-base grant is never withdrawn, and one membership insert empties a group
**Describe the bug**

Two reads in the ServiceNow connector paginate on a `sys_updated_on` watermark
and hand the result to a caller that *replaces* what it finds rather than
merging. The combination loses permissions in both directions.

`_fetch_all_memberships` reads `sys_user_grmember` as a delta.
`on_new_user_groups` then deletes every permission edge pointing at a group
before writing the members it was given. Any group whose membership rows did not
change inside the delta window is written with no members, which empties it.

`_sync_knowledge_bases` reads `kb_knowledge_base` as a delta. A base holds its
read grants in `kb_uc_can_read_mtom`, and adding or removing a grant there does
**not** touch `kb_knowledge_base.sys_updated_on`. So a grant change is invisible
to the delta: a revoked grant stays live indefinitely, and a new grant is never
picked up.

**To Reproduce**

Emptied group:
1. Sync a ServiceNow instance so groups and memberships are indexed, and note
   the members of a group nobody is about to touch.
2. In ServiceNow, insert one `sys_user_grmember` row into a *different* group.
3. Run a routine (delta) sync.
4. The untouched group now has no members, and users who reached articles
   through it can no longer retrieve them.

Revoked grant not withdrawn:
1. Grant a group read access to a knowledge base via `kb_uc_can_read_mtom`, and
   sync.
2. Delete that grant row in ServiceNow.
3. Run any number of delta syncs.
4. The `GROUP` edge on the knowledge base is still there.

**Expected behavior**

A membership that nobody changed keeps its members. A revoked knowledge-base
grant stops granting access after the next ordinary sync.

**Environment**
- OS: Ubuntu 22.04 (Docker deployment)
- Version/Commit ID: reproduced on `v0.6.0` and on `main` at `afcbe76f`
- ServiceNow: developer instance, Knowledge Management, `kb_version 3`

**Additional context**

Measured on a live deployment. One unrelated membership insert followed by one
routine sync:

| | before | after the sync |
| --- | --- | --- |
| members of an untouched 4-member group | 4 | **0** |
| articles a plain user could retrieve | 11 / 11 | **0 / 11** |

The two reads are small. The tested instance holds 54 groups and 606 roles, so
reading them in full is not the cost the delta was presumably added to avoid.

Neither read can be a delta while its caller replaces rather than merges. The
alternative would be to make the caller merge, which is a larger change to
shared code.

I have a fix and will open a PR.

### LINKED ISSUE #3095: [BUG] ServiceNow: an API error mid-pagination is swallowed, so a partial sync reports success
**Describe the bug**

Ten paginated reads in the ServiceNow connector handle a Table API failure the
same way, by logging it and leaving the loop:

```python
except ServiceNowAPIError as e:
    self.logger.error(f"❌ API error: {e.message} (status: {e.status_code})")
    break
```

The sync then continues with whatever arrived before the failure and reports
success. Nothing downstream can tell a short list from a complete one.

For five of them the result is data loss rather than staleness, because the
caller deletes the permission edges of every entity in the list before rewriting
them, so a page that fails partway *removes* access the connector then cannot
rebuild. The others go silently incomplete, and the article and category reads
additionally write a sync checkpoint across the window they never finished, so
those rows are not fetched again until something else changes them.

The record writer has the same silence: `_process_record_updates_batch` drops
any record whose permission list resolves to empty and returns nothing, so the
sync logs more articles than it wrote.

**To Reproduce**

1. Sync an instance with more than one page (100 rows) of `sys_user_grmember`.
2. Make the second page fail. Throttling, a network blip, or a temporary ACL
   change on `sys_user_grmember` will all do it.
3. The sync completes and logs success.
4. Permissions derived from the rows on the failed page are gone, and the next
   delta sync does not restore them because the checkpoint moved.

**Expected behavior**

A read that could not be completed should fail the sync rather than let partial
data through as if it were complete, and should not advance a checkpoint over
rows it never read.

**Environment**
- OS: Ubuntu 22.04 (Docker deployment)
- Version/Commit ID: `v0.6.0` and `main` at `afcbe76f`
- ServiceNow: developer instance, Knowledge Management, `kb_version 3`

**Additional context**

The affected reads:

| function | what a short list costs |
| --- | --- |
| `_fetch_all_memberships`, `_fetch_all_role_assignments`, `_fetch_role_hierarchy`, and the two criteria reads | **permission edges deleted and not rebuilt** |
| `_fetch_all_groups` | groups keep stale memberships |
| `_sync_single_organizational_entity` | companies, departments, locations, cost centres go missing |
| `_sync_knowledge_bases` | knowledge bases and their grants go missing |
| `_sync_categories` | category record groups go missing |
| `_sync_articles` | articles are not indexed, and the checkpoint still advances |

One case should be preserved rather than converted: an empty page from
`kb_knowledge_base` comes back as a body that is not JSON, so `"Expecting value"`
is how that read ends, not a fault.

I have a fix and will open a PR.

### LINKED ISSUE #3096: [BUG] ServiceNow: an indexed record is never rewritten, so article edits never reach search
**Describe the bug**

For a record that already exists, the document write happens in exactly one
place, `_handle_updated_record`, and it is reached only through this test in
`data_source_entities_processor.py`:

```python
if record.external_revision_id != existing_record.external_revision_id:
    await self._handle_updated_record(record, existing_record, tx_store)
```

The ServiceNow connector never sets `external_revision_id`. The string does not
appear anywhere in `connector.py`, so the field keeps its model default of
`None`, `None != None` is false, and for every already-indexed article:

- the stored document is never rewritten, so name, `webUrl` and timestamps all
  keep their first-index values;
- `indexingStatus` stays `COMPLETED`, so no re-index event is published and
  changed content is never re-embedded.

Permissions are unaffected, because `_handle_record_permissions` is called
unconditionally. That asymmetry is why a knowledge-base grant does propagate to
existing articles while the articles themselves stay frozen.

**To Reproduce**

1. Sync a ServiceNow instance and note an article's title in PipesHub.
2. Edit that article's `short_description` in ServiceNow.
3. Run a delta sync. The log reports `Articles synced: 1`, so the connector did
   read the change.
4. The stored record is unchanged, and search still returns the old text.

Note: with knowledge versioning on, a published article cannot be edited through
the Table API at all (`403 ACL Exception`), so step 2 needs a background script
using `gr.setWorkflow(false)`, or an edit through the UI.

**Expected behavior**

An article edited in ServiceNow should have its stored record rewritten and its
content re-embedded on the next sync.

**Environment**
- OS: Ubuntu 22.04 (Docker deployment)
- Version/Commit ID: `v0.6.0` and `main` at `afcbe76f`
- ServiceNow: developer instance, Knowledge Management, `kb_version 3`

**Additional context**

Measured on a live deployment. One published article edited in place:

| | observed |
| --- | --- |
| connector read the change | `Articles synced: 1` |
| stored record | **unchanged** |
| `externalRevisionId` | `None` |

It is worse than staleness: the sync point advanced to the discarded article's
own `sys_updated_on`, so the next delta asked for `sys_updated_on > <that
timestamp>` and correctly returned nothing. **No later delta sync repairs the
record**. Only a full sync, or another edit in ServiceNow, brings it back.

The smallest fix is to populate `external_revision_id` from
`kb_knowledge.sys_updated_on`, which the connector already fetches and which
moves on any write to the row. Note that this means the first sync after such a
fix rewrites and re-embeds every existing article once, since they all currently
carry `None`.

I have a fix and will open a PR.

### PR DESCRIPTION
**Pull request by kemalmahmuljin**
## Description

Eight defects in the ServiceNow connector, found while auditing it against a
ServiceNow developer instance, fixed as three commits.

**First commit, read permission sources in full, not as a delta.** Two reads
paginate on a `sys_updated_on` watermark and hand the result to a caller that
replaces what it finds. `on_new_user_groups` deletes every permission edge
pointing at a group before writing the members it was given, so a delta read
empties every group whose `sys_user_grmember` rows did not change inside the
window. Knowledge bases have the mirror problem: a base holds its read grants in
`kb_uc_can_read_mtom`, and changing a grant there does not touch
`kb_knowledge_base.sys_updated_on`, so a delta never sees a grant added or
revoked. Both reads are now full. Neither can be a delta while its caller
replaces rather than merges, and the volumes are small: groups, memberships,
roles and knowledge bases, rather than articles.

**Second commit, stop a partial read from passing as a complete one.** Ten
paginated reads answered an API error by leaving the loop, so the sync continued
with whatever had arrived and reported success. For five of them the caller then
deletes permission edges it cannot rebuild, so a page that fails partway removes
access. The other five go silently incomplete, and the article and category
reads additionally write a checkpoint across the window they never finished, so
those rows are not fetched again until something else changes them. All ten now
propagate, leaving the checkpoint untouched. One exception is preserved: an
empty page from `kb_knowledge_base` returns a body that is not JSON, so
`"Expecting value"` is how that read ends rather than a fault. The record writer
had the same silence. `_process_record_updates_batch` dropped records whose
permission list came out empty and returned nothing, so the sync logged more
articles than it wrote; it now returns and reports the count.

**Third commit, follow the instance instead of assuming.** Four values were
assumed rather than read from the instance:

- Article, category and KB links were hard-coded to the Service Portal
  (`/sp?id=kb_article&sys_id=`). The knowledge portal is per-instance in
  `sn_km_portal.glide.knowman.serviceportal.portal_url`; on the tested instance
  that is `kb`, giving `/kb?id=kb_article_view&sys_kb_id=`. Every stored link
  pointed at a page that does not serve the article.
- Article *Can Read* criteria were always applied as an override. ServiceNow
  only does that when `glide.knowman.apply_article_read_criteria` is true.
- A refreshed access token was written to `client.access_token` only, while the
  transport authenticates from `client.headers["Authorization"]`, so after a
  refresh every request still carried the old bearer until the process
  restarted.
- `external_revision_id` was never set, so `_handle_updated_record` compared
  `None` to `None` and no existing record was ever rewritten or re-queued.
  Records froze at first index: title, link and content never changed again.

### Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Is there an addition/change in API Request, Response? If yes, documentation is required)
- [ ] Performance improvement
- [ ] Code refactoring
- [ ] Security fix

Two of these restore permission correctness, so they are security adjacent
without being a vulnerability disclosure. The connector was granting access
ServiceNow does not grant, and revoking access ServiceNow still grants.

## Related Issues

- Fixes #3094 (a revoked knowledge-base grant is never withdrawn, and one membership insert empties a group)
- Fixes #3095 (an API error mid-pagination is swallowed, so a partial sync reports success)
- Fixes #3096 (an indexed record is never rewritten, so article edits never reach search)

## How Has This Been Tested?

Two ways: unit tests in the repository, and a live ServiceNow developer instance
with a PipesHub deployment, measured before and after each fix.

The live method was the same each time. Deploy upstream `main`, reproduce the
defect and record the state. Deploy the same image plus the fix, changing
`IMAGE_TAG` only and without restarting the data engines. Repeat the identical
action and record the state again.

### Test Configuration

- [x] Unit tests pass
- [ ] Integration tests pass (not run; no integration suite covers this connector)
- [x] Manual testing completed
- [ ] Cross-browser testing (if applicable) (N/A, no UI change)
- [ ] Mobile responsiveness tested (if applicable) (N/A, no UI change)

## Core Functionality Testing

- [x] **Search capabilities** are working correctly
- [x] **Knowledge search** is functioning properly
- [x] **Connector indexing** is working as expected
- [ ] **Citations** are displaying and linking correctly (link *construction* is
      fixed and verified in the stored record; citation rendering was not tested)
- [ ] **Documentation** is updated (no docs change needed; no API surface changes)

## What You Have Tested

- [x] Feature works in development environment
- [ ] Feature works in staging environment (no staging available)
- [x] Error handling scenarios tested
- [x] Edge cases considered and tested
- [x] Performance impact assessed
- [x] Security implications reviewed

### Test Results

Unit tests, against the three ServiceNow test files plus everything else that
imports the connector:

```
upstream main   531 passed
this PR         548 passed
```

Each commit passes on its own (534 → 536 → 548). Three failures are present both
before and after, in `test_all_apps.py` for Box, MinIO and Google Cloud Storage,
which fail on missing optional dependencies (`box_sdk_gen`, `aioboto3`,
`google.api_core`) and are unrelated to this change.

Ruff on the three changed source files: **98 findings, down from 101 on
upstream `main`**. No new rule violations.

#### The tests, before and after

Checking out this branch's tests against upstream's source, so the tests exist
but the fixes do not, **45 ServiceNow tests fail**, and each fails with the
defect it describes rather than with an import or setup error:

| witness test | failure against upstream `main` |
| --- | --- |
| `test_reads_every_row` | `TypeError: 'coroutine' object is not iterable` |
| `test_knowledge_base_query_carries_no_delta_even_with_a_sync_point` | `assert 'sys_updated_on>' not in 'sys_updated…'` |
| `test_a_failed_page_does_not_yield_a_partial_membership_list` | `Failed: DID NOT RAISE ServiceNowAPIError` |
| `test_process_record_updates_batch_reports_dropped_records` | `assert None == 1` |
| `test_article_url_uses_the_resolved_portal` | `assert '…/sp?id=kb_article&sys_id=art1' == '…/kb?id=kb_article_view&sys_kb_id=art1'` |
| `test_own_criteria_stop_the_inheritance_when_the_property_is_on` | `assert True is False` |
| `test_set_access_token_rewrites_the_authorization_header` | `AttributeError: … object has no attribute 'set_access_token'` |
| `test_article_carries_a_revision_id` | `assert None == '2026-08-26 09:15:00'` |

Reproduce it with:

```bash
git checkout <this-branch>
git checkout origin/main -- backend/python/app/connectors/sources/servicenow/ \
                            backend/python/app/sources/client/servicenow/
cd backend/python && pytest tests/unit/connectors/sources/test_servicenow_connector*.py
```

Some existing tests also changed, because they asserted the defective behaviour.
Two examples worth naming, since they show why these defects survived:

- one asserted that a failed page returns an empty list, so it passed whether
  the read failed on page 1 or page 40, and could not tell a partial sync from a
  complete one;
- one asserted that a refreshed token lands on `client.access_token`, which was
  true the whole time every request still carried the stale bearer. The token
  bug had test coverage, and the coverage is why nobody noticed.

**Memberships destroyed by the delta read.** Inserting one unrelated membership
row, then running one routine sync:

| | upstream `main` | with the fix |
| --- | --- | --- |
| members of a 4-member group after the sync | **0** | **4, intact** |
| articles a plain user could retrieve | 11 / 11 → **0 / 11** | 11 / 11 → **11 / 11** |

**Knowledge-base grant revoked in ServiceNow**, then one routine delta sync:

| Time (UTC) | Grant in ServiceNow | KB `GROUP` edges |
| --- | --- | --- |
| 16:06:46 | present | 1 |
| 16:07:53 | **deleted** | n/a |
| 16:08:54 | absent | **0, withdrawn in 25 s** |

On upstream `main` that edge stayed at 1 indefinitely.

**Article links.** Two probe articles, identical but for the build that indexed
them:

| Probe | Indexed by | Stored `webUrl` |
| --- | --- | --- |
| A | upstream `main` | `/sp?id=kb_article&sys_id=…` |
| B | with the fix | `/kb?id=kb_article_view&sys_kb_id=…` |

The `/kb` was read from the instance, not hard-coded. Instance configuration
confirming what "correct" is: `sn_km_portal.glide.knowman.serviceportal.portal_url = kb`,
while the default portal in `sp_portal` is `esc`.

**Article read criteria.** One article whose own *Can Read* criteria name a
group the reader is not in, with the reader holding a knowledge-base grant:

| `glide.knowman.apply_article_read_criteria` | ServiceNow serves it | PipesHub, upstream | PipesHub, fixed |
| --- | --- | --- | --- |
| `false` (instance default) | yes | not returned | **returned** |
| `true` | no | not returned | **not returned** |

**Records never rewritten.** One published article edited in place:

| | upstream `main` | with the fix |
| --- | --- | --- |
| connector read the change | `Articles synced: 1` | `Articles synced: 1` |
| stored record | **unchanged** | title updated, `version 0 → 1`, re-indexed |
| `externalRevisionId` | `None` | `2026-08-27 08:42:17`, equal to `sys_updated_on` |

Worse than staleness: the sync point advanced to the discarded article's own
`sys_updated_on`, so no later delta sync could repair it.

## Screenshots/Videos

N/A, no UI change. Evidence is the recorded state above, taken from the graph
and from the connector logs.

## Code Quality Checklist

- [x] My code follows the project's coding standards
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (none needed)
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

Each fix has tests that fail without it. Several existing tests asserted the
defective behaviour and were rewritten to the new contract. One asserted that a
failed page returns an empty list. Another asserted that a refreshed token lands
on `client.access_token`, which was true while every request still carried the
stale bearer.

## Documentation

- [ ] Documentation has been updated (if applicable) (not applicable)
- [ ] API documentation updated (if applicable) (no API surface change)
- [ ] README updated (if applicable) (not applicable)
- [ ] Changelog updated (if applicable) (happy to add one if the project wants it)

## Security Considerations

- [x] No sensitive data is exposed
- [x] Input validation is implemented where necessary
- [x] Authentication/authorization is properly handled
- [x] No security vulnerabilities introduced

Two of the fixes change who can retrieve what, in both directions: a revoked
knowledge-base grant is now withdrawn, and article read criteria are applied
only when the instance says they should be. Both were verified against what
ServiceNow itself serves to the same user, rather than against an assumption.

## Breaking Changes

- [ ] This PR introduces breaking changes
- [ ] Migration guide provided (if applicable)
- [ ] Version bump required

No API or schema change. Two behaviour changes are worth calling out even though
neither breaks a contract:

1. A sync that hits an API error now **fails** rather than completing with
   partial data. This is the point of the change, but an operator used to green
   syncs may see red ones where the data was previously wrong and silent.
2. Existing records carry `external_revision_id = None`, so the first sync after
   deploying rewrites and re-embeds **every** article once.

## Performance Impact

- [ ] No performance impact
- [ ] Performance improved
- [x] Performance impact assessed and acceptable

Two full reads replace delta reads, over groups, memberships, roles and
knowledge bases, which are small tables. On the tested instance: 54 groups, 606 roles.

The one-time re-index above is the real cost. Fifty-four articles on the tested
instance. On a large tenant it is a full re-embed, once.

## Dependencies

- [x] No new dependencies added
- [ ] New dependencies are necessary and approved
- [ ] Dependencies updated and tested

## Deployment Notes

Expect one full re-index of ServiceNow articles on the first sync after
deploying, caused by `external_revision_id` moving from unset to a real value.
No configuration change is required. The connector reads two instance
properties it previously ignored, `sn_km_portal.glide.knowman.serviceportal.portal_url`
and `glide.knowman.apply_article_read_criteria`, and falls back to the previous
behaviour if either is absent.

## Additional Notes

Scope is confined to the ServiceNow connector: `connector.py`, `constants.py`,
and one purely additive method on `sources/client/servicenow/servicenow.py`
(`set_access_token`, which no other caller relies on).

Every measurement above comes from one ServiceNow developer instance running the
Knowledge Management application with `kb_version 3` (knowledge versioning on).
Behaviour that depends on instance configuration, meaning the knowledge portal
and the read-criteria property, is read from the instance rather than assumed,
but has only been observed on that one instance.

## Summary by CodeRabbit

- **New Features**
  - ServiceNow knowledge-base, category, and article links now use the configured knowledge portal.
  - Article and attachment records include revision information for more reliable updates.
  - Article permission settings, including read criteria, are applied consistently to attachments.

- **Bug Fixes**
  - ServiceNow access-token refreshes now apply immediately to subsequent requests.
  - Synchronization failures are surfaced instead of silently producing incomplete results.
  - Full synchronization improves data completeness for groups, roles, memberships, and knowledge bases.

### CODE REVIEW

**Comment by abhishek-pipeshub** [comment]
@kemalmahmuljin Can you please look into the review comments and also attach testing evidence screenshots

**Review by abhishek-pipeshub — APPROVED** [review]
